In [1]:
import pandas as pd

Alright so importing pandas let's have a look at each file and identify usefel vocabularies and objects for our graph.

In [2]:
nutrition = pd.read_csv('Nutrition.csv', delimiter=';')

In [3]:
# nutrition

identify classes and properties:

In [4]:
recipes = pd.read_csv('Recipes.csv', delimiter=';')
recipes.shape

(522517, 13)

In [5]:
recipes

,RecipeId,Name,CookTime,PrepTime,DatePublished,Images,RecipeCategory,Keywords,RecipeIngredientQuantities,RecipeIngredientParts,RecipeServings,RecipeYield,RecipeInstructions
0,38,Low-Fat Berry Blue Frozen Dessert,PT24H,PT45M,1999-08-09T21:46:00Z,"c(""https://img.sndimg.com/food/image/upload/w_...",Frozen Desserts,"c(""Dessert"", ""Low Protein"", ""Low Cholesterol"",...","c(""4"", ""1/4"", ""1"", ""1"")","c(""blueberries"", ""granulated sugar"", ""vanilla ...",4.0,NaN,"c(""Toss 2 cups berries with sugar."", ""Let stan..."
1,39,Biryani,PT25M,PT4H,1999-08-29T13:12:00Z,"c(""https://img.sndimg.com/food/image/upload/w_...",Chicken Breast,"c(""Chicken Thigh & Leg"", ""Chicken"", ""Poultry"",...","c(""1"", ""4"", ""2"", ""2"", ""8"", ""1/4"", ""8"", ""1/2"", ...","c(""saffron"", ""milk"", ""hot green chili peppers""...",6.0,NaN,"c(""Soak saffron in warm milk for 5 minutes and..."
2,40,Best Lemonade,PT5M,PT30M,1999-09-05T19:52:00Z,"c(""https://img.sndimg.com/food/image/upload/w_...",Beverages,"c(""Low Protein"", ""Low Cholesterol"", ""Healthy"",...","c(""1 1/2"", ""1"", NA, ""1 1/2"", NA, ""3/4"")","c(""sugar"", ""lemons, rind of"", ""lemon, zest of""...",4.0,NaN,"c(""Into a 1 quart Jar with tight fitting lid, ..."
3,41,Carina's Tofu-Vegetable Kebabs,PT20M,PT24H,1999-09-03T14:54:00Z,"c(""https://img.sndimg.com/food/image/upload/w_...",Soy/Tofu,"c(""Beans"", ""Vegetable"", ""Low Cholesterol"", ""We...","c(""12"", ""1"", ""2"", ""1"", ""10"", ""1"", ""3"", ""2"", ""2...","c(""extra firm tofu"", ""eggplant"", ""zucchini"", ""...",2.0,4 kebabs,"c(""Drain the tofu, carefully squeezing out exc..."
4,42,Cabbage Soup,PT30M,PT20M,1999-09-19T06:19:00Z,"""https://img.sndimg.com/food/image/upload/w_55...",Vegetable,"c(""Low Protein"", ""Vegan"", ""Low Cholesterol"", ""...","c(""46"", ""4"", ""1"", ""2"", ""1"")","c(""plain tomato juice"", ""cabbage"", ""onion"", ""c...",4.0,NaN,"c(""Mix everything together and bring to a boil..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
522512,541379,Meg's Fresh Ginger Gingerbread,PT35M,PT1H,2020-12-22T15:27:00Z,character(0),Dessert,"""< 4 Hours""","c(""3"", ""1/2"", ""1/2"", ""1/4"", ""1/4"", ""1"", ""1/4"",...","c(""fresh ginger"", ""unsalted butter"", ""dark bro...",8.0,1 8x8 cake pan,"c(""Preheat oven to 350&deg;F Grease an 8x8 cak..."
522513,541380,Roast Prime Rib au Poivre with Mixed Peppercorns,PT3H,PT30M,2020-12-22T15:32:00Z,"""https://img.sndimg.com/food/image/upload/w_55...",Very Low Carbs,"c(""High Protein"", ""High In..."", ""< 4 Hours"")","c(""9"", ""2"", ""4"", ""2"", ""1/3"", ""3 1/2"", ""1/3"")","c(""Dijon mustard"", ""garlic"", ""peppercorns"", ""s...",8.0,1 Roast,"c(""Position rack in center of oven and preheat..."
522514,541381,Kirshwasser Ice Cream,PT3H,PT1H,2020-12-22T15:33:00Z,character(0),Ice Cream,"c(""Dessert"", ""< 4 Hours"")","c(""3"", ""3"", ""1/2"", ""1/2"", ""2"", ""2"")","c(""half-and-half"", ""heavy cream"", ""brandy"", ""s...",6.0,NaN,"c(""heat half and half and heavy cream to a sim..."
522515,541382,Quick & Easy Asian Cucumber Salmon Rolls,NaN,PT15M,2020-12-22T22:11:00Z,"""https://img.sndimg.com/food/image/upload/w_55...",Canadian,"c(""< 15 Mins"", ""Easy"")","c(""4"", ""1/4"", ""1"", ""1/2"", ""8 1/2"", ""40"")","c(""wasabi paste"", ""dill"", ""English cucumber"", ...",NaN,20 rolls,"c(""In a small bowl, combine mayo and wasabi pa..."
522516,541383,Spicy Baked Scotch Eggs,PT25M,PT15M,2020-12-22T22:12:00Z,character(0),Breakfast,"""< 60 Mins""","c(""6 -7"", ""1"", ""1/4"", ""1"", ""2"", ""1/2"", ""1"", ""1...","c(""hard-boiled eggs"", ""breakfast sausage"", ""pa...",NaN,NaN,"c(""Mix sausage, panko, egg yolk and Wocestersh..."

In [6]:
recipes['Name'] = recipes['Name'].str.lower()
nutrition['Name'] = nutrition['Name'].str.lower()

recipes_not_in_nutrition = recipes[~recipes['Name'].isin(nutrition['Name'])]

nutrition_not_in_recipes = nutrition[~nutrition['Name'].isin(recipes['Name'])]

print("Recipes not in Nutrition:")
print(recipes_not_in_nutrition)

print("\nNutrition not in Recipes:")
print(nutrition_not_in_recipes)

Recipes not in Nutrition:
        RecipeId                                              Name CookTime  \
81411      86478                          classic chocolate mousse      NaN
81412      86479                         raspberry sour cream tart     PT4H
81414      86481                                  mexican chex mix     PT5M
81415      86482                              noodles with chicken    PT15M
81416      86483                            quick cherry turnovers    PT10M
...          ...                                               ...      ...
522512    541379                    meg's fresh ginger gingerbread    PT35M
522513    541380  roast prime rib au poivre with mixed peppercorns     PT3H
522514    541381                             kirshwasser ice cream     PT3H
522515    541382          quick & easy asian cucumber salmon rolls      NaN
522516    541383                           spicy baked scotch eggs    PT25M

       PrepTime         DatePublished  \
81411     PT15M  2004-03-13T19:59:00Z
81412     PT15M  2004-03-13T19:59:00Z
81414      PT5M  2004-03-13T19:59:00Z
81415     PT10M  2004-03-13T19:59:00Z
81416      PT8M  2004-03-13T19:59:00Z
...         ...                   ...
522512     PT1H  2020-12-22T15:27:00Z
522513    PT30M  2020-12-22T15:32:00Z
522514     PT1H  2020-12-22T15:33:00Z
522515    PT15M  2020-12-22T22:11:00Z
522516    PT15M  2020-12-22T22:12:00Z

                                                   Images     RecipeCategory  \
81411   c("https://img.sndimg.com/food/image/upload/w_...            Dessert
81412                                        character(0)              Tarts
81414                                        character(0)  Southwestern U.S.
81415                                        character(0)            Chicken
81416                                        character(0)          Breakfast
...                                                   ...                ...
522512                                       character(0)            Dessert
522513  "https://img.sndimg.com/food/image/upload/w_55...     Very Low Carbs
522514                                       character(0)          Ice Cream
522515  "https://img.sndimg.com/food/image/upload/w_55...           Canadian
522516                                       character(0)          Breakfast

                                                 Keywords  \
81411          c("European", "Kid Friendly", "< 15 Mins")
81412   c("Dessert", "Raspberries", "Berries", "Fruit"...
81414   c("Mexican", "Spicy", "Savory", "< 15 Mins", "...
81415   c("Poultry", "Vegetable", "Meat", "Low Cholest...
81416   c("Cherries", "Fruit", "Healthy", "Kid Friendl...
...                                                   ...
522512                                        "< 4 Hours"
522513       c("High Protein", "High In...", "< 4 Hours")
522514                          c("Dessert", "< 4 Hours")
522515                             c("< 15 Mins", "Easy")
522516                                        "< 60 Mins"

                               RecipeIngredientQuantities  \
81411   c("6", "3/4", "2", "2", "1/3", "1", "1/2", "1/...
81412   c("8", "1/4", "1/4", "6", "1/3", "1/2", "2", "...
81414              c("8", "4", "2", "1", "3", "1/3", "1")
81415                   c("2", "8", "1", "1", "1", "1/2")
81416                      c("1", "1", "1/2", "1", "1/2")
...                                                   ...
522512  c("3", "1/2", "1/2", "1/4", "1/4", "1", "1/4",...
522513       c("9", "2", "4", "2", "1/3", "3 1/2", "1/3")
522514                c("3", "3", "1/2", "1/2", "2", "2")
522515           c("4", "1/4", "1", "1/2", "8 1/2", "40")
522516  c("6 -7", "1", "1/4", "1", "2", "1/2", "1", "1...

                                    RecipeIngredientParts  RecipeServings  \
81411   c("brandy", "sugar", "vanilla extract", "sugar...             4.0
81412   c("graham crackers", "golden brown sugar", "un...             8.0
81414         c("margarine", "butter", "parmesan cheese")            52.0
81415   c("carrots", "sugar snap peas", "mandarin oran...             4.0
81416   c("cherry pie filling", "confectioners' sugar"...             4.0
...                                                   ...             ...
522512  c("fresh ginger", "unsalted butter", "dark bro...             8.0
522513  c("Dijon mustard", "garlic", "peppercorns", "s...             8.0
522514  c("half-and-half", "heavy cream", "brandy", "s...             6.0
522515  c("wasabi paste", "dill", "English cucumber", ...             NaN
522516  c("hard-boiled eggs", "breakfast sausage", "pa...             NaN

           RecipeYield                                 RecipeInstructions
81411              NaN  c("For mousse: Heat whipping cream gently in d...
81412              NaN  c("For crust; preheat oven to 375*F.", "Grind ...
81414          26 cups  c("Mix dry ingredients in large resealable pla...
81415              NaN  c("Cook spaghetti in a large pot of boiling sa...
81416              NaN  c("Unroll dough and separate.", "Make 4 square...
...                ...                                                ...
522512  1 8x8 cake pan  c("Preheat oven to 350&deg;F Grease an 8x8 cak...
522513         1 Roast  c("Position rack in center of oven and preheat...
522514             NaN  c("heat half and half and heavy cream to a sim...
522515        20 rolls  c("In a small bowl, combine mayo and wasabi pa...
522516             NaN  c("Mix sausage, panko, egg yolk and Wocestersh...

[392752 rows x 13 columns]

Nutrition not in Recipes:
Empty DataFrame
Columns: [Name, Description, RecipeCategory, Calories, FatContent, SaturatedFatContent, CholesterolContent, SodiumContent, CarbohydrateContent, FiberContent, SugarContent, ProteinContent]
Index: []

In [7]:
nutrition_unique = nutrition.drop_duplicates(subset='Name')
nutrition_unique.shape

(72428, 12)

In [8]:
recipes_with_nutrition = recipes.merge(nutrition_unique, on='Name', how='left')

In [9]:
# print("Merged DataFrame:")
# # recipes_with_nutrition = recipes_with_nutrition.dropna()
# recipes_with_nutrition

In [10]:
recipes_with_nutrition.rename(columns={'RecipeCategory_x': 'RecipeCategory'}, inplace=True)
recipes_with_nutrition.drop(columns='RecipeCategory_y', inplace=True)

In [11]:
# Convert 'name' column to lowercase
recipes['Name'] = recipes['Name'].str.lower()
nutrition['Name'] = nutrition['Name'].str.lower()

# Find names in recipes not in nutrition
recipes_not_in_nutrition = recipes[~recipes['Name'].isin(nutrition['Name'])]

# Find names in nutrition not in recipes
nutrition_not_in_recipes = nutrition[~nutrition['Name'].isin(recipes['Name'])]

# Display results
print("Recipes not in Nutrition:")
print(recipes_not_in_nutrition)

print("\nNutrition not in Recipes:")
print(nutrition_not_in_recipes)

Recipes not in Nutrition:
        RecipeId                                              Name CookTime  \
81411      86478                          classic chocolate mousse      NaN
81412      86479                         raspberry sour cream tart     PT4H
81414      86481                                  mexican chex mix     PT5M
81415      86482                              noodles with chicken    PT15M
81416      86483                            quick cherry turnovers    PT10M
...          ...                                               ...      ...
522512    541379                    meg's fresh ginger gingerbread    PT35M
522513    541380  roast prime rib au poivre with mixed peppercorns     PT3H
522514    541381                             kirshwasser ice cream     PT3H
522515    541382          quick & easy asian cucumber salmon rolls      NaN
522516    541383                           spicy baked scotch eggs    PT25M

       PrepTime         DatePublished  \
81411     PT15M  2004-03-13T19:59:00Z
81412     PT15M  2004-03-13T19:59:00Z
81414      PT5M  2004-03-13T19:59:00Z
81415     PT10M  2004-03-13T19:59:00Z
81416      PT8M  2004-03-13T19:59:00Z
...         ...                   ...
522512     PT1H  2020-12-22T15:27:00Z
522513    PT30M  2020-12-22T15:32:00Z
522514     PT1H  2020-12-22T15:33:00Z
522515    PT15M  2020-12-22T22:11:00Z
522516    PT15M  2020-12-22T22:12:00Z

                                                   Images     RecipeCategory  \
81411   c("https://img.sndimg.com/food/image/upload/w_...            Dessert
81412                                        character(0)              Tarts
81414                                        character(0)  Southwestern U.S.
81415                                        character(0)            Chicken
81416                                        character(0)          Breakfast
...                                                   ...                ...
522512                                       character(0)            Dessert
522513  "https://img.sndimg.com/food/image/upload/w_55...     Very Low Carbs
522514                                       character(0)          Ice Cream
522515  "https://img.sndimg.com/food/image/upload/w_55...           Canadian
522516                                       character(0)          Breakfast

                                                 Keywords  \
81411          c("European", "Kid Friendly", "< 15 Mins")
81412   c("Dessert", "Raspberries", "Berries", "Fruit"...
81414   c("Mexican", "Spicy", "Savory", "< 15 Mins", "...
81415   c("Poultry", "Vegetable", "Meat", "Low Cholest...
81416   c("Cherries", "Fruit", "Healthy", "Kid Friendl...
...                                                   ...
522512                                        "< 4 Hours"
522513       c("High Protein", "High In...", "< 4 Hours")
522514                          c("Dessert", "< 4 Hours")
522515                             c("< 15 Mins", "Easy")
522516                                        "< 60 Mins"

                               RecipeIngredientQuantities  \
81411   c("6", "3/4", "2", "2", "1/3", "1", "1/2", "1/...
81412   c("8", "1/4", "1/4", "6", "1/3", "1/2", "2", "...
81414              c("8", "4", "2", "1", "3", "1/3", "1")
81415                   c("2", "8", "1", "1", "1", "1/2")
81416                      c("1", "1", "1/2", "1", "1/2")
...                                                   ...
522512  c("3", "1/2", "1/2", "1/4", "1/4", "1", "1/4",...
522513       c("9", "2", "4", "2", "1/3", "3 1/2", "1/3")
522514                c("3", "3", "1/2", "1/2", "2", "2")
522515           c("4", "1/4", "1", "1/2", "8 1/2", "40")
522516  c("6 -7", "1", "1/4", "1", "2", "1/2", "1", "1...

                                    RecipeIngredientParts  RecipeServings  \
81411   c("brandy", "sugar", "vanilla extract", "sugar...             4.0
81412   c("graham crackers", "golden brown sugar", "un...             8.0
81414         c("margarine", "butter", "parmesan cheese")            52.0
81415   c("carrots", "sugar snap peas", "mandarin oran...             4.0
81416   c("cherry pie filling", "confectioners' sugar"...             4.0
...                                                   ...             ...
522512  c("fresh ginger", "unsalted butter", "dark bro...             8.0
522513  c("Dijon mustard", "garlic", "peppercorns", "s...             8.0
522514  c("half-and-half", "heavy cream", "brandy", "s...             6.0
522515  c("wasabi paste", "dill", "English cucumber", ...             NaN
522516  c("hard-boiled eggs", "breakfast sausage", "pa...             NaN

           RecipeYield                                 RecipeInstructions
81411              NaN  c("For mousse: Heat whipping cream gently in d...
81412              NaN  c("For crust; preheat oven to 375*F.", "Grind ...
81414          26 cups  c("Mix dry ingredients in large resealable pla...
81415              NaN  c("Cook spaghetti in a large pot of boiling sa...
81416              NaN  c("Unroll dough and separate.", "Make 4 square...
...                ...                                                ...
522512  1 8x8 cake pan  c("Preheat oven to 350&deg;F Grease an 8x8 cak...
522513         1 Roast  c("Position rack in center of oven and preheat...
522514             NaN  c("heat half and half and heavy cream to a sim...
522515        20 rolls  c("In a small bowl, combine mayo and wasabi pa...
522516             NaN  c("Mix sausage, panko, egg yolk and Wocestersh...

[392752 rows x 13 columns]

Nutrition not in Recipes:
Empty DataFrame
Columns: [Name, Description, RecipeCategory, Calories, FatContent, SaturatedFatContent, CholesterolContent, SodiumContent, CarbohydrateContent, FiberContent, SugarContent, ProteinContent]
Index: []

As we can see here each nutrition has a recipe but not each recipe has a nutrition so we can merge nutrition on recipe we will be left with NaNs for the recipes without nutrition but that is completely fine knowledge graphs can handle this. 
Now for the construction of the KG we need some way to link recipes to their nutrition however nutrition can have more than one entry for a dish, but these are not uniquely traceable back to their original recipe thus I cant identify which nutrition of a dish belongs to a specific recipe, therefore I assume each dish has the same nutrition but can have several recipes otherwise it would be impossible or too difficult to identify wich belong to which. Therefore I will also drop duplicate entries in the nutrition table to be inline with this assumption of only having one nutrition for a dish. After dropping I will perform a left outerjoin on recipes with nutrition to make one table for ease of knowledge graph construction.

Now one more standardization is I will put the ingredients and quatities together, one downside is we are not given units for the amount of an ingredient so this will be missing in the data but one can most likely infer from the ingredient what unit it should be if there is a NaN value it will simple be taken over so we might have just the ingredient or only the amount.

In [12]:
import re


def sanitize_name(name):
    # Lowercase and strip whitespace
    name = name.strip().lower()
    # Replace spaces with underscores
    name = re.sub(r'\s+', '_', name)
    # Optionally remove characters that aren't alphanumeric or underscores/hyphens
    name = re.sub(r'[^\w-]', '', name)
    return name


recipes_with_nutrition['Name'] = recipes_with_nutrition['Name'].apply(sanitize_name)

In [13]:
def parse_r_vector(r_vector_str):
    """Removes the leading 'c(' and trailing ')' and splits the string into a list."""
    # If the input is not a string, return an empty list
    if not isinstance(r_vector_str, str):
        return []
    cleaned = re.sub(r"^c\(|\)$", "", r_vector_str)
    # Split on comma+space and remove any remaining quotes and whitespace
    items = [item.strip().strip('"').strip("'") for item in cleaned.split(", ")]
    return items


def combine_ingredients(row):
    """Combine quantities and ingredients for a given row."""
    # Since the columns have already been parsed, they are now lists
    quantities = row['RecipeIngredientQuantities']
    ingredients = row['RecipeIngredientParts']
    return [f"{qty} {ing}" for qty, ing in zip(quantities, ingredients)]


# Edit: Johannes I will create a new Dataframe here from the recipe_with_nutritions thing

# convert into correct format from r vector to list
# recipes_with_nutrition_copy = recipes_with_nutrition.copy()
# recipes_with_nutrition_copy['RecipeIngredientQuantities'] = recipes_with_nutrition_copy[
#     'RecipeIngredientQuantities'].apply(
#     parse_r_vector)
# recipes_with_nutrition_copy['RecipeIngredientParts'] = recipes_with_nutrition_copy['RecipeIngredientParts'].apply(
#     parse_r_vector)

# filter out rows where quantity and ingredients do not match
# recipes_with_nutrition_copy = recipes_with_nutrition_copy[
#     recipes_with_nutrition_copy['RecipeIngredientQuantities'].apply(len) == recipes_with_nutrition_copy[
#         'RecipeIngredientParts'].apply(len)]

# explode the list to get unique rows
# recipes_with_nutrition_copy = recipes_with_nutrition_copy.explode(
# ['RecipeIngredientQuantities', 'RecipeIngredientParts'])

# Rename columns
# recipes_with_nutrition_copy = recipes_with_nutrition_copy.rename(
# columns={'RecipeIngredientQuantities': 'Quantity', 'RecipeIngredientParts': 'Ingredient'})

# recipes_ingredients_dataframe = recipes_with_nutrition_copy[["RecipeId", 'Quantity', 'Ingredient']]

# Actually make sure that formatting is consisent by stripping leading and trailing whitespaces and lower casing

# recipes_ingredients_dataframe["Ingredient"] = recipes_ingredients_dataframe["Ingredient"].str.lower().str.strip()

# Apply the function to each row to create a new column "Ingredients"
recipes_with_nutrition['RecipeIngredientQuantities'] = recipes_with_nutrition['RecipeIngredientQuantities'].apply(
    parse_r_vector)
recipes_with_nutrition['RecipeIngredientParts'] = recipes_with_nutrition['RecipeIngredientParts'].apply(parse_r_vector)
recipes_with_nutrition['Keywords'] = recipes_with_nutrition['Keywords'].apply(parse_r_vector)
recipes_with_nutrition['Ingredients'] = recipes_with_nutrition.apply(combine_ingredients, axis=1)

# Drop the now unnecessary columns
# recipes_with_nutrition.drop(columns=['RecipeIngredientQuantities', 'RecipeIngredientParts'], inplace=True)

# Save into .csv
# recipes_ingredients_dataframe.to_csv("Ingredients.csv", index=False)
# Clear from Cache
recipes_with_nutrition_copy = None

In [14]:
recipes_with_nutrition

,RecipeId,Name,CookTime,PrepTime,DatePublished,Images,RecipeCategory,Keywords,RecipeIngredientQuantities,RecipeIngredientParts,...,Calories,FatContent,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,Ingredients
0,38,low-fat_berry_blue_frozen_dessert,PT24H,PT45M,1999-08-09T21:46:00Z,"c(""https://img.sndimg.com/food/image/upload/w_...",Frozen Desserts,"[Dessert, Low Protein, Low Cholesterol, Health...","[4, 1/4, 1, 1]","[blueberries, granulated sugar, vanilla yogurt...",...,170.9,2.5,1.3,8.0,29.8,37.1,3.6,30.2,3.2,"[4 blueberries, 1/4 granulated sugar, 1 vanill..."
1,39,biryani,PT25M,PT4H,1999-08-29T13:12:00Z,"c(""https://img.sndimg.com/food/image/upload/w_...",Chicken Breast,"[Chicken Thigh & Leg, Chicken, Poultry, Meat, ...","[1, 4, 2, 2, 8, 1/4, 8, 1/2, 1, 1, 1/4, 1/4, 1...","[saffron, milk, hot green chili peppers, onion...",...,1110.7,58.8,16.6,372.8,368.4,84.4,9.0,20.4,63.4,"[1 saffron, 4 milk, 2 hot green chili peppers,..."
2,40,best_lemonade,PT5M,PT30M,1999-09-05T19:52:00Z,"c(""https://img.sndimg.com/food/image/upload/w_...",Beverages,"[Low Protein, Low Cholesterol, Healthy, Summer...","[1 1/2, 1, NA, 1 1/2, NA, 3/4]","[sugar, lemons, rind of, lemon, zest of, fresh...",...,311.1,0.2,0.0,0.0,1.8,81.5,0.4,77.2,0.3,"[1 1/2 sugar, 1 lemons, NA rind of, 1 1/2 lemo..."
3,41,carinas_tofu-vegetable_kebabs,PT20M,PT24H,1999-09-03T14:54:00Z,"c(""https://img.sndimg.com/food/image/upload/w_...",Soy/Tofu,"[Beans, Vegetable, Low Cholesterol, Weeknight,...","[12, 1, 2, 1, 10, 1, 3, 2, 2, 2, 1, 2, 1/2, 1/...","[extra firm tofu, eggplant, zucchini, mushroom...",...,536.1,24.0,3.8,0.0,1558.6,64.2,17.3,32.1,29.3,"[12 extra firm tofu, 1 eggplant, 2 zucchini, 1..."
4,42,cabbage_soup,PT30M,PT20M,1999-09-19T06:19:00Z,"""https://img.sndimg.com/food/image/upload/w_55...",Vegetable,"[Low Protein, Vegan, Low Cholesterol, Healthy,...","[46, 4, 1, 2, 1]","[plain tomato juice, cabbage, onion, carrots, ...",...,103.6,0.4,0.1,0.0,959.3,25.1,4.8,17.7,4.3,"[46 plain tomato juice, 4 cabbage, 1 onion, 2 ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522512,541379,megs_fresh_ginger_gingerbread,PT35M,PT1H,2020-12-22T15:27:00Z,character(0),Dessert,[< 4 Hours],"[3, 1/2, 1/2, 1/4, 1/4, 1, 1/4, 1 1/2, 1, 1/2,...","[fresh ginger, unsalted butter, dark brown sug...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[3 fresh ginger, 1/2 unsalted butter, 1/2 dark..."
522513,541380,roast_prime_rib_au_poivre_with_mixed_peppercorns,PT3H,PT30M,2020-12-22T15:32:00Z,"""https://img.sndimg.com/food/image/upload/w_55...",Very Low Carbs,"[High Protein, High In..., < 4 Hours]","[9, 2, 4, 2, 1/3, 3 1/2, 1/3]","[Dijon mustard, garlic, peppercorns, shallot, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[9 Dijon mustard, 2 garlic, 4 peppercorns, 2 s..."
522514,541381,kirshwasser_ice_cream,PT3H,PT1H,2020-12-22T15:33:00Z,character(0),Ice Cream,"[Dessert, < 4 Hours]","[3, 3, 1/2, 1/2, 2, 2]","[half-and-half, heavy cream, brandy, sugar]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[3 half-and-half, 3 heavy cream, 1/2 brandy, 1..."
522515,541382,quick__easy_asian_cucumber_salmon_rolls,NaN,PT15M,2020-12-22T22:11:00Z,"""https://img.sndimg.com/food/image/upload/w_55...",Canadian,"[< 15 Mins, Easy]","[4, 1/4, 1, 1/2, 8 1/2, 40]","[wasabi paste, dill, English cucumber, smoked ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[4 wasabi paste, 1/4 dill, 1 English cucumber,..."
522516,541383,spicy_baked_scotch_eggs,PT25M,PT15M,2020-12-22T22:12:00Z,character(0),Breakfast,[< 60 Mins],"[6 -7, 1, 1/4, 1, 2, 1/2, 1, 1, 1 -2]","[hard-boiled eggs, breakfast sausage, panko br...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[6 -7 hard-boiled eggs, 1 breakfast sausage, 1..."

In [15]:
recipes_ingredients_dataframe = pd.read_csv('Ingredients.csv')

In [16]:
print(recipes_ingredients_dataframe.shape)
recipes_ingredients_dataframe.head()

(966164, 3)

   RecipeId Quantity          Ingredient
0        38        4         blueberries
1        38      1/4    granulated sugar
2        38        1      vanilla yogurt
3        38        1         lemon juice
4        42       46  plain tomato juice

In [17]:
distinct_recipes = recipes_ingredients_dataframe['RecipeId'].nunique()
print("Number of distinct recipes:", distinct_recipes)

Number of distinct recipes: 115665

In [18]:
# Count how often an Ingredient appears
recipes_ingredients_dataframe["Ingredient"].value_counts()

Ingredient
salt                                                 53564
butter                                               35208
sugar                                                29838
water                                                19345
olive oil                                            19006
                                                     ...
rice pie crust                                           1
diced tomatoes with green pepper celery and onion        1
prepared honey-dijon barbecue sauce                      1
canned corn niblet                                       1
lamb loin chop                                           1
Name: count, Length: 5340, dtype: int64

We also drop RecipeServings as its contained within RecipeYield which has a defined schema on schema.org.

In [19]:
recipes_with_nutrition.drop(columns='RecipeServings', inplace=True)

In [20]:
restaurants = pd.read_csv('Restaurants.csv', delimiter=';')

In [21]:
restaurants.head()

,Restaurant ID,Restaurant Name,Country,City,Address,Locality Verbose,Longitude,Latitude,Cuisines,Currency,...,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,Nummber of dishes in cuisines,Average cost of two in USD
0,1600219,12212,India,Nashik,"Shop 10, Ramrajya Building 7, Samarth Nagar, N...","College Road, Nashik",73.754636,20.006690,Fast Food,Indian Rupees(Rs.),...,0,0,0,2,3.5,3.70,3,80,1,4.664
1,17057397,'Ohana,USA,Orlando,"1600 Seven Seas Drive, Lake Buena Vista, FL 32830","Disney World Area, Orlando",-81.585226,28.405437,Hawaiian,Dollar($),...,0,0,0,3,4.5,4.65,5,1151,1,45.000
2,18222559,{Niche} - Cafe & Bar,India,New Delhi,"2nd & 3rd Floor, M-16, M Block, Outer Circle, ...","Connaught Place, New Delhi",77.222507,28.631516,"North Indian, Chinese, Italian, Continental",Indian Rupees(Rs.),...,0,0,0,3,4.1,4.25,4,492,4,17.490
3,113702,@Mango,India,Ahmedabad,"Opposite Sindhu Bhawan, Bodakdev, Ahmedabad","Bodakdev, Ahmedabad",72.501764,23.040163,"North Indian, Continental, Mexican, Italian",Indian Rupees(Rs.),...,0,0,0,3,4.1,4.25,4,769,4,9.328
4,3100446,#45,India,Mangalore,"Ground Floor, Trinity Commercial Complex, Near...","Attavar, Mangalore",0.000000,0.000000,Cafe,Indian Rupees(Rs.),...,0,0,0,2,3.6,3.70,3,209,1,6.996

In [22]:

def parse_cuisines(cuisine_str):
    """
    Converts a string of cuisines into a list of cuisines.
    
    Parameters:
        cuisine_str (str): A string containing one or more cuisines,
                           separated by commas if multiple.
    
    Returns:
        list: A list of cuisines (each cuisine is stripped of extra whitespace).
    """
    # Check for missing or non-string values
    if not isinstance(cuisine_str, str) or not cuisine_str.strip():
        return []

    # Split on comma and strip whitespace from each cuisine
    return [cuisine.strip() for cuisine in cuisine_str.split(',')]


restaurants['Cuisine_List'] = restaurants['Cuisines'].apply(parse_cuisines)

In [23]:
restaurants.drop(columns=['Rating color', 'Rating text'], inplace=True)

In [24]:
reviews = pd.read_csv('Reviews.csv', delimiter=',')
reviews

,ReviewId,RecipeId,AuthorId,AuthorName,Review,DateSubmitted,DateModified
0,2,992,2008,gayg msft,better than any you can get at a restaurant!,2000-01-25 21:44:00+00:00,2000-01-25 21:44:00+00:00
1,9,4523,2046,Gay Gilmore ckpt,i think i did something wrong because i could ...,2000-02-25 09:00:00+00:00,2000-02-25 09:00:00+00:00
2,14,44,2085,Tony Small,An excellent dish.,2000-03-28 12:51:00+00:00,2000-03-28 12:51:00+00:00
3,21,148,2156,Darlene Blythe,Would someone please check the Nutrition Facts...,2000-06-02 10:01:00+00:00,2000-06-02 10:01:00+00:00
4,22,517,2046,Gay Gilmore ckpt,thought this was terrific!,2000-02-25 09:02:00+00:00,2000-02-25 09:02:00+00:00
...,...,...,...,...,...,...,...
126500,407322,207312,67656,justcallmetoni,I saw this and decided it would be a fun optio...,2007-04-29 03:22:34+00:00,2007-04-29 03:22:34+00:00
126501,407326,122528,29782,Marsha D.,Wonderful dip! Made for opening weekend for fi...,2007-04-29 03:58:50+00:00,2007-04-29 03:58:50+00:00
126502,407328,44366,29782,Marsha D.,Simple and easy recipe. I used this in Recipe ...,2007-04-29 04:03:03+00:00,2007-04-29 04:03:03+00:00
126503,407329,135203,139238,Tonyjillshy,"""These were very good. Not your basic boring c...",2007-04-29 04:06:39+00:00,2007-04-29 04:06:39+00:00
126504,407330,46353,135887,VA3212,Excellent. Easy to make and delicious! Thank ...,2007-04-29 04:08:09+00:00,2007-04-29 04:08:09+00:00

Some dateSubmitted values didnt parse correctly so I will manually put them to the modified date as there was probably an issue where if the data wasnt modified the delimiter got confused. there will be some loss in the review but that is an acceptable loss formatting the Reviews.txt into a csv was a struggle.

In [25]:
reviews['ParsedDateSubmitted'] = pd.to_datetime(reviews['DateSubmitted'],
                                                format="%Y-%m-%dT%H:%M:%SZ",
                                                errors='coerce')

invalid_mask = reviews['ParsedDateSubmitted'].isna()

reviews.loc[invalid_mask, 'DateSubmitted'] = reviews.loc[invalid_mask, 'DateModified']

In [26]:
reviews.drop(columns='ParsedDateSubmitted', inplace=True)

In [27]:
reviews

,ReviewId,RecipeId,AuthorId,AuthorName,Review,DateSubmitted,DateModified
0,2,992,2008,gayg msft,better than any you can get at a restaurant!,2000-01-25 21:44:00+00:00,2000-01-25 21:44:00+00:00
1,9,4523,2046,Gay Gilmore ckpt,i think i did something wrong because i could ...,2000-02-25 09:00:00+00:00,2000-02-25 09:00:00+00:00
2,14,44,2085,Tony Small,An excellent dish.,2000-03-28 12:51:00+00:00,2000-03-28 12:51:00+00:00
3,21,148,2156,Darlene Blythe,Would someone please check the Nutrition Facts...,2000-06-02 10:01:00+00:00,2000-06-02 10:01:00+00:00
4,22,517,2046,Gay Gilmore ckpt,thought this was terrific!,2000-02-25 09:02:00+00:00,2000-02-25 09:02:00+00:00
...,...,...,...,...,...,...,...
126500,407322,207312,67656,justcallmetoni,I saw this and decided it would be a fun optio...,2007-04-29 03:22:34+00:00,2007-04-29 03:22:34+00:00
126501,407326,122528,29782,Marsha D.,Wonderful dip! Made for opening weekend for fi...,2007-04-29 03:58:50+00:00,2007-04-29 03:58:50+00:00
126502,407328,44366,29782,Marsha D.,Simple and easy recipe. I used this in Recipe ...,2007-04-29 04:03:03+00:00,2007-04-29 04:03:03+00:00
126503,407329,135203,139238,Tonyjillshy,"""These were very good. Not your basic boring c...",2007-04-29 04:06:39+00:00,2007-04-29 04:06:39+00:00
126504,407330,46353,135887,VA3212,Excellent. Easy to make and delicious! Thank ...,2007-04-29 04:08:09+00:00,2007-04-29 04:08:09+00:00

In [28]:
# First, convert the columns to datetime objects with UTC awareness
reviews['DateSubmitted'] = pd.to_datetime(reviews['DateSubmitted'], utc=True)
reviews['DateModified'] = pd.to_datetime(reviews['DateModified'], utc=True)

# Then, format them to strings with 'Z' at the end instead of '+00:00'
reviews['DateSubmitted'] = reviews['DateSubmitted'].dt.strftime('%Y-%m-%dT%H:%M:%SZ')
reviews['DateModified'] = reviews['DateModified'].dt.strftime('%Y-%m-%dT%H:%M:%SZ')

In [29]:
reviews

,ReviewId,RecipeId,AuthorId,AuthorName,Review,DateSubmitted,DateModified
0,2,992,2008,gayg msft,better than any you can get at a restaurant!,2000-01-25T21:44:00Z,2000-01-25T21:44:00Z
1,9,4523,2046,Gay Gilmore ckpt,i think i did something wrong because i could ...,2000-02-25T09:00:00Z,2000-02-25T09:00:00Z
2,14,44,2085,Tony Small,An excellent dish.,2000-03-28T12:51:00Z,2000-03-28T12:51:00Z
3,21,148,2156,Darlene Blythe,Would someone please check the Nutrition Facts...,2000-06-02T10:01:00Z,2000-06-02T10:01:00Z
4,22,517,2046,Gay Gilmore ckpt,thought this was terrific!,2000-02-25T09:02:00Z,2000-02-25T09:02:00Z
...,...,...,...,...,...,...,...
126500,407322,207312,67656,justcallmetoni,I saw this and decided it would be a fun optio...,2007-04-29T03:22:34Z,2007-04-29T03:22:34Z
126501,407326,122528,29782,Marsha D.,Wonderful dip! Made for opening weekend for fi...,2007-04-29T03:58:50Z,2007-04-29T03:58:50Z
126502,407328,44366,29782,Marsha D.,Simple and easy recipe. I used this in Recipe ...,2007-04-29T04:03:03Z,2007-04-29T04:03:03Z
126503,407329,135203,139238,Tonyjillshy,"""These were very good. Not your basic boring c...",2007-04-29T04:06:39Z,2007-04-29T04:06:39Z
126504,407330,46353,135887,VA3212,Excellent. Easy to make and delicious! Thank ...,2007-04-29T04:08:09Z,2007-04-29T04:08:09Z

In [30]:
reviews_mentions = pd.read_csv("Review_Mentions.csv")
reviews_mentions['ReviewId'] = reviews_mentions['ReviewId'].astype(int)
reviews_mentions.head()

   ReviewId    mentions
0         9  cornstarch
1        23        lime
2        25   mushrooms
3        25     sausage
4        25     chicken

In [31]:
reviews_mentions.dtypes

ReviewId     int32
mentions    object
dtype: object

In [32]:
reviews_sentiment = pd.read_csv("Reviews_with_Sentiment.csv")
reviews_sentiment[["ReviewId", "RecipeId", "AuthorId"]] = reviews_sentiment[
    ["ReviewId", "RecipeId", "AuthorId"]].astype(int)
reviews_sentiment.head()

,ReviewId,RecipeId,AuthorId,AuthorName,Review,DateSubmitted,DateModified,sentiment,confidence
0,2,992,2008,gayg msft,better than any you can get at a restaurant!,2000-01-25 21:44:00+00:00,2000-01-25 21:44:00+00:00,positive,0.90
1,9,4523,2046,Gay Gilmore ckpt,i think i did something wrong because i could ...,2000-02-25 09:00:00+00:00,2000-02-25 09:00:00+00:00,negative,0.85
2,14,44,2085,Tony Small,An excellent dish.,2000-03-28 12:51:00+00:00,2000-03-28 12:51:00+00:00,positive,0.90
3,21,148,2156,Darlene Blythe,Would someone please check the Nutrition Facts...,2000-06-02 10:01:00+00:00,2000-06-02 10:01:00+00:00,error,0.00
4,22,517,2046,Gay Gilmore ckpt,thought this was terrific!,2000-02-25 09:02:00+00:00,2000-02-25 09:02:00+00:00,positive,0.90

In [33]:

def lower_space(name):
    name = name.strip().lower()
    name = re.sub(r'\s+', '_', name)

    return name

In [34]:
import rdflib
from rdflib import Graph, Namespace, URIRef, Literal, RDF, RDFS, OWL
from rdflib.namespace import DCTERMS, XSD, RDF, SDO, RDFS, SKOS

In [35]:
ex = Namespace("http://kg-course/food-nutrition/")

# Create Graph
gr = rdflib.Namespace("http://purl.org/goodrelations/v1#")
dbo = rdflib.Namespace("http://dbpedia.org/ontology/")
dbr = rdflib.Namespace("http://dbpedia.org/resource/")

g = Graph()
g.bind("dbo", dbo)
g.bind("dbr", dbr)
g.bind("rdf", RDF)
g.bind("rdfs", RDFS)
g.bind("gr", gr)
g.bind("owl", OWL)
g.bind("xsd", XSD)
g.bind("schema", SDO)
g.bind("skos", SKOS)
g.bind("ex", ex)

#The following classes and properties already exist in schema.org ontologies thus I wont be redifing them here however I will list them as they will be used
'''
classes
schema:Recipe
schema:Restaurant
OWL:Thing
schema:Review
schema:rating
schema:Person



properties
#for recipes
we drop recipeServings as its essentially equivalent to recipeYield.
name
recipeInstructions
cookTime
prepTime
image
datePublished
recipeYield
recipeCategory
recipeIngredient

#for nutrition
calories	
fatContent	
saturatedFatContent
cholesterolContent	
sodiumContent	
carbohydrateContent	
fiberContent	
sugarContent	
proteinContent

#for restaurant 
servesCuisine
location
address
legalName
lonngitude
latitude
currenciesAccepted
priceRange
we choose to combine avergacostof2 and currency for priceRange as text.

#for reviews
review
itemReviewed
author
ratingValue
datePublished
dateSubmitted
reviewBody
alternateName

'''

#Defining all the classes
#dish
g.add((ex.Dish, RDF.type, RDFS.Class))
g.add((ex.Dish, RDFS.label, Literal('Dish')))
g.add((ex.Dish, RDFS.comment, Literal('Something consumed when famished.')))
g.add((ex.Dish, RDFS.subClassOf, OWL.Thing))

#cuisine
g.add((ex.Cuisine, RDF.type, RDFS.Class))
g.add((ex.Cuisine, RDFS.label, Literal('Cuisine')))
g.add((ex.Cuisine, RDFS.comment, Literal('A type of cuisine typically belonging to a restaurant or recipe')))
g.add((ex.Cuisine, RDFS.subClassOf, OWL.Thing))

#NutritionInformation
g.add((ex.NutritionInfo, RDF.type, RDFS.Class))
g.add((ex.NutritionInfo, RDFS.label, Literal('NutritionInfo')))
g.add((ex.NutritionInfo, RDFS.comment, Literal("Nutritional information for a dish.")))
g.add((ex.NutritionInfo, OWL.equivalentClass, SDO.NutritionInformation))

#Ingredient
g.add((ex.Ingredient, RDF.type, RDFS.Class))
g.add((ex.Ingredient, RDFS.label, Literal('Ingredient')))
g.add((ex.Ingredient, RDFS.comment, Literal('Ingredient used in a recipe')))
g.add((ex.Ingredient, RDFS.subClassOf, OWL.Thing))

#Defining all the properties
#nutrition
g.add((ex.nutrition, RDF.type, RDF.Property))
g.add((ex.nutrition, RDFS.domain, ex.Dish))
g.add((ex.nutrition, RDFS.range, ex.NutritionInfo))
g.add((ex.nutrition, RDFS.label, Literal('nutrition')))
g.add((ex.nutrition, RDFS.comment, Literal('Links a dish to its nutrition info.')))
g.add((ex.nutrition, SKOS.closeMatch, SDO.nutrition))

#hasRecipe
g.add((ex.hasRecipe, RDF.type, RDF.Property))
g.add((ex.hasRecipe, RDFS.domain, ex.Dish))
g.add((ex.hasRecipe, RDFS.range, SDO.Recipe))
g.add((ex.hasRecipe, RDFS.label, Literal('hasRecipe')))
g.add((ex.hasRecipe, RDFS.comment, Literal('Links a dish to its recipe, a dish may have several recipes.')))

#inCOuntry
g.add((ex.inCountry, RDF.type, RDF.Property))
g.add((ex.inCountry, RDFS.domain, SDO.Restaurant))
g.add((ex.inCountry, RDFS.range, XSD.string))
g.add((ex.inCountry, RDFS.label, Literal('InCountry')))
g.add((ex.inCountry, RDFS.comment, Literal('Links a restaurant to its country of origin.')))
g.add((ex.inCountry, SKOS.closeMatch, SDO.addressCountry))

#hasTableBooking
#hasDelivery
g.add((ex.hasTableBooking, RDF.type, RDF.Property))
g.add((ex.hasTableBooking, RDFS.domain, SDO.Restaurant))
g.add((ex.hasTableBooking, RDFS.range, XSD.boolean))
g.add((ex.hasTableBooking, RDFS.label, Literal('hasTableBooking')))
g.add((ex.hasTableBooking, RDFS.comment, Literal('Links a restaurant to its ability to be able to book a table.')))

#hasDelivery
g.add((ex.hasDelivery, RDF.type, RDF.Property))
g.add((ex.hasDelivery, RDFS.domain, SDO.Restaurant))
g.add((ex.hasDelivery, RDFS.range, XSD.boolean))
g.add((ex.hasDelivery, RDFS.label, Literal('hasDelivery')))
g.add((ex.hasDelivery, RDFS.comment,
       Literal('Links a restaurant to its ability to deliver food to your house via online order.')))

#isDeliveringNow
g.add((ex.isDeliveringNow, RDF.type, RDF.Property))
g.add((ex.isDeliveringNow, RDFS.domain, SDO.Restaurant))
g.add((ex.isDeliveringNow, RDFS.range, XSD.boolean))
g.add((ex.isDeliveringNow, RDFS.label, Literal('isDeliveringNow')))
g.add((ex.isDeliveringNow, RDFS.comment, Literal('Links a restaurant to the fact if its delivering now.')))

#switchToOrderMenu
g.add((ex.switchToOrderMenu, RDF.type, RDF.Property))
g.add((ex.switchToOrderMenu, RDFS.domain, SDO.Restaurant))
g.add((ex.switchToOrderMenu, RDFS.range, XSD.boolean))
g.add((ex.switchToOrderMenu, RDFS.label, Literal('switchToOrderMenu')))
g.add(
    (ex.switchToOrderMenu, RDFS.comment, Literal('The availibility to have the ability to switch to the order menu.')))

#avgRating
g.add((ex.avgRating, RDF.type, RDF.Property))
g.add((ex.avgRating, RDFS.domain, SDO.Restaurant))
g.add((ex.avgRating, RDFS.range, XSD.double))
g.add((ex.avgRating, RDFS.label, Literal('avgRating')))
g.add((ex.avgRating, RDFS.comment, Literal('The average rating given to a restaurant by customers.')))
g.add((ex.avgRating, SKOS.closeMatch, SDO.ratingValue))

#votes
g.add((ex.votes, RDF.type, RDF.Property))
g.add((ex.votes, RDFS.domain, SDO.Restaurant))
g.add((ex.votes, RDFS.range, XSD.integer))
g.add((ex.votes, RDFS.label, Literal('votes')))
g.add((ex.votes, RDFS.comment, Literal('Amount of reviews received')))
g.add((ex.votes, SKOS.closeMatch, SDO.reviewCount))

#numberOfDishes
g.add((ex.numberOfDishes, RDF.type, RDF.Property))
g.add((ex.numberOfDishes, RDFS.domain, SDO.Restaurant))
g.add((ex.numberOfDishes, RDFS.range, XSD.integer))
g.add((ex.numberOfDishes, RDFS.label, Literal('numberOfDishes')))
g.add((ex.numberOfDishes, RDFS.comment, Literal('Amount of unque dishes served by a restaurant.')))

#hasCuisine
g.add((ex.hasCuisine, RDF.type, RDF.Property))
g.add((ex.hasCuisine, RDFS.domain, SDO.Restaurant))
g.add((ex.hasCuisine, RDFS.range, ex.Cuisine))
g.add((ex.hasCuisine, RDFS.label, Literal('hasCuisine')))
g.add((ex.hasCuisine, RDFS.comment, Literal('Links a restaurant a cuisine it servers.')))
g.add((ex.hasCuisine, SKOS.closeMatch, SDO.servesCuisine))

#containsIngredient
g.add((ex.containsIngredient, RDF.type, RDF.Property))
g.add((ex.containsIngredient, RDFS.domain, SDO.Recipe))
g.add((ex.containsIngredient, RDFS.range, ex.Ingredient))
g.add((ex.containsIngredient, RDFS.label, Literal('containsIngredient')))
g.add((ex.containsIngredient, RDFS.comment, Literal('Links an ingredient to its recipe.')))
g.add((ex.containsIngredient, SKOS.closeMatch, SDO.recipeIngredient))

In [36]:
# g.serialize(destination="vocabulary.ttl", format="turtle")

In [37]:
# recipes_with_nutrition

In [38]:
# reviews.dtypes

In [39]:
# row = recipes_with_nutrition.iloc[0]
# for entry in row['Ingredients']:
#     print(entry.format, entry)

In [40]:
def add_triples(g=None, recipes_with_nutrition=None, reviews=None, restaurants=None, amount=10000):
    # lets start adding everything to the graph please keep my comments
    dish_instances = {}  # keep track of dishes I've seen
    ingredient_instances = {}

    if recipes_with_nutrition is not None:
        for index, row in recipes_with_nutrition.iloc[:amount].iterrows():
            # create dishes
            if not pd.isna(row['Name']):
                dish = row['Name']
                if dish not in dish_instances:
                    dish_uri = ex[dish]
                    dish_instances[dish] = dish_uri

                    # create dish
                    g.add((dish_uri, RDF.type, ex.Dish))
                    # add nutritionInformation
                    nutrition_info_uri = ex[f'{dish}_nutritionInfo']
                    g.add((nutrition_info_uri, RDF.type, ex.NutritionInfo))
                    g.add((dish_uri, ex.nutrition, nutrition_info_uri))
                    # add all information to nutritionInformation
                    if not pd.isna(row['Calories']):
                        g.add((nutrition_info_uri, SDO.calories, Literal(row['Calories'], datatype=XSD.float)))

                    if not pd.isna(row['FatContent']):
                        g.add((nutrition_info_uri, SDO.fatContent, Literal(row['FatContent'], datatype=XSD.float)))

                    if not pd.isna(row['SaturatedFatContent']):
                        g.add((nutrition_info_uri, SDO.saturatedFatContent,
                               Literal(row['SaturatedFatContent'], datatype=XSD.float)))

                    if not pd.isna(row['CholesterolContent']):
                        g.add((nutrition_info_uri, SDO.cholesterolContent,
                               Literal(row['CholesterolContent'], datatype=XSD.float)))

                    if not pd.isna(row['SodiumContent']):
                        g.add(
                            (nutrition_info_uri, SDO.sodiumContent, Literal(row['SodiumContent'], datatype=XSD.float)))

                    if not pd.isna(row['CarbohydrateContent']):
                        g.add((nutrition_info_uri, SDO.carbohydrateContent,
                               Literal(row['CarbohydrateContent'], datatype=XSD.float)))

                    if not pd.isna(row['FiberContent']):
                        g.add((nutrition_info_uri, SDO.fiberContent, Literal(row['FiberContent'], datatype=XSD.float)))

                    if not pd.isna(row['SugarContent']):
                        g.add((nutrition_info_uri, SDO.sugarContent, Literal(row['SugarContent'], datatype=XSD.float)))

                    if not pd.isna(row['ProteinContent']):
                        g.add((nutrition_info_uri, SDO.proteinContent,
                               Literal(row['ProteinContent'], datatype=XSD.float)))

                    # add description to dish
                    if not pd.isna(row['Description']):
                        g.add((dish_uri, SDO.description, Literal(row['Description'], datatype=XSD.string)))

            # create recipeId TYPE
            recipe_uri = ex['recipe_' + str(row["RecipeId"])]
            g.add((recipe_uri, RDF.type, SDO.Recipe))
            # Name
            if not pd.isna(row['Name']):
                g.add((recipe_uri, SDO.name, Literal(row['Name'], datatype=XSD.string)))
                # add recipe as one of the recipes for a dish
                g.add((ex[row['Name']], ex.hasRecipe, recipe_uri))
            # cookTime
            if not pd.isna(row['CookTime']):
                g.add((recipe_uri, SDO.cookTime, Literal(row['CookTime'], datatype=XSD.duration)))
            # prepTime
            if not pd.isna(row['PrepTime']):
                g.add((recipe_uri, SDO.prepTime, Literal(row['PrepTime'], datatype=XSD.duration)))
            # datePublished
            if not pd.isna(row['DatePublished']):
                g.add((recipe_uri, SDO.datePublished,
                       Literal(row['DatePublished'], datatype=XSD.dateTime)))
            # images
            if not pd.isna(row['Images']):
                g.add((recipe_uri, SDO.image, Literal(row['Images'], datatype=XSD.anyURI)))
            # recipecategory
            if not pd.isna(row['RecipeCategory']):
                g.add((recipe_uri, SDO.recipeCategory,
                       Literal(row['RecipeCategory'], datatype=XSD.string)))
                # Keywords
            if not pd.isna(row['Keywords']).any():
                for keyword in row['Keywords']:
                    g.add(
                        (recipe_uri, SDO.keywords, Literal(keyword, datatype=XSD.string)))
            # recipeYield
            if not pd.isna(row['RecipeYield']):
                g.add((recipe_uri, SDO.recipeYield, Literal(row['RecipeYield'], datatype=XSD.string)))
            # RecipeInstructions  
            if not pd.isna(row['RecipeInstructions']):
                g.add((recipe_uri, SDO.recipeInstructions,
                       Literal(row['RecipeInstructions'], datatype=XSD.string)))
            # Ingredients
            if not pd.isna(row['RecipeIngredientParts']).any():
                for ingredient in row['RecipeIngredientParts']:
                    ingredient = lower_space(ingredient)
                    ingredient_uri = 'Ingredient_' + ingredient
                    if ingredient not in ingredient_instances:
                        ingredient_uri = ex[ingredient]
                        dish_instances[dish] = dish_uri
                        g.add((ingredient_uri, RDF.type, ex['Ingredient']))
                        g.add((ingredient_uri, RDFS.label, Literal(ingredient, datatype=XSD.string)))
                    g.add((recipe_uri, ex['containsIngredient'], ingredient_uri))

    if reviews is not None:
        for index, row in reviews.iloc[:amount].iterrows():
            review_uri = ex["review_" + str(row['ReviewId'])]
            g.add((review_uri, RDF.type, SDO.Review))
            g.add((ex['recipe_' + str(row["RecipeId"])], SDO.review, review_uri))
            g.add(
                (review_uri, SDO.datePublished, Literal(row['DateSubmitted'], datatype=XSD.dateTime)))
            g.add((review_uri, SDO.dateModified, Literal(row['DateModified'], datatype=XSD.dateTime)))
            g.add((review_uri, SDO.reviewBody, Literal(row['Review'], datatype=XSD.string)))

            # add author and person
            # I use alternateName here since its an alias.
            author_uri = ex["author_" + str(row['AuthorId'])]
            g.add((author_uri, RDF.type, SDO.Person))
            g.add((author_uri, SDO.alternateName, Literal(row['AuthorName'], datatype=XSD.string)))

            # now we can add the author of review
            g.add((review_uri, SDO.author, author_uri))

    if restaurants is not None:
        for index, row in restaurants.iloc[:amount].iterrows():
            restaurant_uri = ex['restaurant_' + str(row['Restaurant ID'])]
            g.add((restaurant_uri, RDF.type, SDO.Restaurant))

            if not pd.isna(row['Restaurant Name']):
                g.add((restaurant_uri, SDO.legalName,
                       Literal(row['Restaurant Name'], datatype=XSD.string)))

            # Country
            if not pd.isna(row['Country']):
                g.add(
                    (restaurant_uri, ex.inCountry, Literal(row['Country'], datatype=XSD.string)))

            # City
            if not pd.isna(row['City']):
                g.add(
                    (restaurant_uri, SDO.areaServed, Literal(row['City'], datatype=XSD.string)))

            # address
            if not pd.isna(row['Address']):
                g.add(
                    (restaurant_uri, SDO.address, Literal(row['Address'], datatype=XSD.string)))

            # locality
            if not pd.isna(row['Locality Verbose']):
                g.add((restaurant_uri, SDO.location,
                       Literal(row['Locality Verbose'], datatype=XSD.string)))

            # longitude
            if not pd.isna(row['Longitude']):
                g.add((restaurant_uri, SDO.longitude,
                       Literal(row['Longitude'], datatype=XSD.float)))

            # latitude
            if not pd.isna(row['Latitude']):
                g.add(
                    (restaurant_uri, SDO.latitude, Literal(row['Latitude'], datatype=XSD.float)))

            # cuisines
            if not pd.isna(row['Cuisine_List']).any():
                for cuisine in row['Cuisine_List']:
                    cuisine = sanitize_name(cuisine)
                    cuisine_uri = ex['is_' + cuisine]
                    g.add((cuisine_uri, RDF.type, ex.Cuisine))
                    g.add((restaurant_uri, ex.hasCuisine, cuisine_uri))
                    g.add((cuisine_uri, RDFS.label, Literal(cuisine, datatype=XSD.string)))

            # currencies
            if not pd.isna(row['Currency']):
                g.add((restaurant_uri, SDO.currenciesAccepted,
                       Literal(row['Currency'], datatype=XSD.string)))

            # tableBooking
            if not pd.isna(row['Has Table booking']):
                g.add((restaurant_uri, ex.hasTableBooking,
                       Literal(bool(row['Has Table booking']), datatype=XSD.boolean)))

            # online delivery
            if not pd.isna(row['Has Online delivery']):
                g.add((restaurant_uri, ex.hasDelivery,
                       Literal(bool(row['Has Online delivery']), datatype=XSD.boolean)))

            # Is delivering now
            if not pd.isna(row['Is delivering now']):
                g.add((restaurant_uri, ex.isDeliveringNow,
                       Literal(bool(row['Is delivering now']), datatype=XSD.boolean)))

            # Switch to order menu
            if not pd.isna(row['Switch to order menu']):
                g.add((restaurant_uri, ex.switchToOrderMenu,
                       Literal(bool(row['Switch to order menu']), datatype=XSD.boolean)))

            # priceRange
            if not pd.isna(row['Average cost of two in USD']):
                g.add((restaurant_uri, SDO.priceRange,
                       Literal(str(row['Average cost of two in USD']), datatype=XSD.string)))

            # aggregate rating
            if not pd.isna(row['Aggregate rating']):
                g.add((restaurant_uri, ex.avgRating,
                       Literal(float(row['Aggregate rating']), datatype=XSD.double)))

            # votes
            if not pd.isna(row['Votes']):
                g.add(
                    (restaurant_uri, ex.votes, Literal(int(row['Votes']), datatype=XSD.integer)))

            # number of dishes
            if not pd.isna(row['Nummber of dishes in cuisines']):
                g.add((restaurant_uri, ex.numberOfDishes,
                       Literal(int(row['Nummber of dishes in cuisines']), datatype=XSD.integer)))

In [41]:
amount_triples_per_table = 1000000
# add_triples(g=g, recipes_with_nutrition=recipes_with_nutrition, reviews=reviews, restaurants=restaurants,
#             amount=amount_triples_per_table)

In [42]:
g.serialize(destination="full_graph.ttl", format="turtle")

# Find all reviews with sentiment that we also  added to the graph

In [43]:
triples_added = recipes_with_nutrition.iloc[:amount_triples_per_table]
merged_df = pd.merge(triples_added, reviews_sentiment, on='RecipeId', how='left')

# Keep only the desired columns
final_df = merged_df[['RecipeId', 'ReviewId', 'sentiment', 'confidence']].dropna()
final_df['ReviewId'] = final_df['ReviewId'].astype(int)

In [44]:
review_mentions = reviews_mentions.merge(final_df, on='ReviewId', how='left')

In [45]:
print(review_mentions["mentions"].value_counts().head(100))
print(len(review_mentions["mentions"].value_counts().head(100)))

mentions
chicken       266
cheese        223
garlic        167
potatoes      119
butter        113
             ...
lettuce         9
oregano         9
greens          8
applesauce      8
rhubarb         8
Name: count, Length: 100, dtype: int64
100

In [46]:
final_df  #TODO CREATE PROPERTIES AND CLASS FOR REVIEW TO GET A RATING OBJECT AND ITS SCORES

       RecipeId  ReviewId sentiment  confidence
6            44        14  positive        0.90
58          100        76  positive        0.90
85          129       810  positive        0.90
101         148        21     error        0.00
106         153        84  positive        0.95
...         ...       ...       ...         ...
5825       8766       699  positive        0.90
5840       8781       742  positive        0.90
5846       8787       740  positive        0.80
9014      12134       335  positive        0.90
13374     16599       689  positive        0.80

[245 rows x 4 columns]

In [47]:
# time = restaurants['Nummber of dishes in cuisines'].iloc[1]
# print(time)
# time.format